name: Update Readmes

on: [repository_dispatch, workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: npm i

      - name: Build
        run: npm run sync

      - name: Push
        run: |
          git config --global user.email "docs@escolalms.com"
          git config --global user.name "Wellms Documentation Bot"
          git add . && git commit -am "Updating .md files from Organization Repositories"
          git push
